# Dataset in use
data:
  name: vrd
  with_bg_obj: False
  with_bg_pred: False

  justafew : False

# Architecture (or model) type
model:
  # Constructor
  type: DSRModel
  # Modalities (features) used by the model
  feat_used:
    # Use visual features
    vis: True
    # In addition to the visual features of the union box
    #  use those of subject and object individually?
    vis_so: True
    # Use semantic features (TOD: this becomes the size of the semantic features)
    sem: True
    # Three types of spatial feature:
    # - False: no spatial info
    # - dsr_spat_vec : 8-way relative location vector
    # - dsr_spat_mat : dual mask # TODO
    spat: dsr_spat_mat
  # Use or not predicate semantics
  use_pred_sem: False

  # Size of the representation for each modality when fusing features
  n_fus_neurons: 256
  # Use batch normalization or not
  use_bn: False

# Evaluation Arguments
eval:
  justafew: False
  test_pre: True
  test_rel: True
  use_obj_prior: True
  use_preload: False
  eval_obj: True
  # R@x metrics
  rec: [100, 50]

opt:
  lr: 0.00001
  # momentum: 0.9
  weight_decay: 0.0005

# Training parameters
training:
  # Adjust learning rate every lr_decay_step epochs
  # TODO: check if this work: #lr_decay_step: 3
  #lr_decay_gamma: .1
  use_shuffle: True
  num_epochs: 6
  checkpoint_freq: 0
  # Number of lines printed with loss ...TODO explain smart freq
  print_freq: 0.1
  # TODO
  batch_size: 1
  loss: mlab
  # loss: mse
  use_preload: False

  test_first: False
  test_freq: 1
